### ISSUE TITLE
show_image method will return an error may be a bug

### ISSUE THREAD

**Issue by COD1995** [d2l-ai/d2l-en#2247] opened 2022-08-12 00:31 UTC
In TensorFlow
`
TypeError: Invalid shape (28, 28, 1) for image data
`

This error will come up when running the code `data.visualize()` in the notebook.

**Comment by astonzhang** [comment] 2022-08-12 03:22
Thanks. Could you be more specific on which line of code in which notebook? Besides, please also share `pip show tensorflow` output so we know the version.

**Comment by AnirudhDagar** [comment] 2022-08-13 21:04
Thanks @COD1995 for reporting the problem and filing the issue. It really helps us improve the book.

**Locally**

I'm using `tensorflow==2.9.1` as suggested in our [requirements](https://github.com/d2l-ai/d2l-en/blob/2f7c62cc1dc3f30a35a43a3e75c349d7782252f5/static/build.yml#L11), and everything works perfectly for that.

Just to be double sure, I also installed `tensorflow==2.8.2` to mimic your environment, and the code seems fine.

**Colab**

I was able to reproduce the problem when running on colab. Initially it seemed to be the version difference. But after further investigation, I found the root cause. `colab` is using `python 3.7` and installs fairly old libraries `numpy==1.21.6`, `matplotlib==3.2.2` whereas locally, I had the latest version of libraries (same as we set for d2l requirements).

---

Digging further, I found that a [silent squeeze was introduced](https://github.com/matplotlib/matplotlib/blob/5b5cc0ecda2c116db7d7866de4d87e635d71380d/lib/matplotlib/image.py#L704)  if the third dimension is 1 in the following PR:

https://github.com/matplotlib/matplotlib/pull/15090  (corresponding issue discussion https://github.com/matplotlib/matplotlib/issues/15089).

This is precisely the point of difference. This change was released in v3.3.0 (See release [notes](https://matplotlib.org/3.3.0/users/whats_new.html#imshow-now-coerces-3d-arrays-with-depth-1-to-2d).). I'm surprised that the matplotlib devs did not put this change in the [release highlights](https://github.com/matplotlib/matplotlib/releases/tag/v3.3.0).

---

Anyway, I'll send a fix for this now in the master branch. @COD1995 till then you could: 

Manually do the squeeze for the fix:
`d2l.show_images(tf.squeeze(X), nrows, ncols, titles=labels)`

or

Upgrade your `matplotlib` version: `pip install --upgrade matplotlib>=3.3`

**Closed** 2022-08-16 22:40 UTC
Labels: tensorflow
