### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. 

### ISSUE THREAD

**Issue by gladex** [d2l-ai/d2l-en#2183] opened 2022-07-04 00:27 UTC
After successfully installed, but when running
`from d2l import torch as d2l`
it returns the error as below,
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 4>()
      1 #import torch
      2 #print(torch.__version__)
----> 4 from d2l import torch as d2l

File /opt/anaconda3/envs/D2L/lib/python3.10/site-packages/d2l/torch.py:32, in <module>
     30 import zipfile
     31 from collections import defaultdict
---> 32 import pandas as pd
     33 import requests
     34 from IPython import display

File /opt/anaconda3/envs/D2L/lib/python3.10/site-packages/pandas/__init__.py:29, in <module>
     22 from pandas.compat.numpy import (
     23     np_version_under1p17 as _np_version_under1p17,
     24     np_version_under1p18 as _np_version_under1p18,
     25     is_numpy_dev as _is_numpy_dev,
     26 )
     28 try:
---> 29     from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
     30 except ImportError as e:  # pragma: no cover
     31     # hack but overkill to use re
     32     module = str(e).replace("cannot import name ", "")

File /opt/anaconda3/envs/D2L/lib/python3.10/site-packages/pandas/_libs/__init__.py:13, in <module>
      1 __all__ = [
      2     "NaT",
      3     "NaTType",
   (...)
      9     "Interval",
     10 ]
---> 13 from pandas._libs.interval import Interval
     14 from pandas._libs.tslibs import (
     15     NaT,
     16     NaTType,
   (...)
     21     iNaT,
     22 )

File pandas/_libs/interval.pyx:1, in init pandas._libs.interval()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

---------------------------------------------------------------------------

It seems the panda or numpy included in `d2l` is old a bit. Any suggestion will be greatly appreciated.

**Comment by AnirudhDagar** [comment] 2022-07-06 19:38
Hi, @gladex thanks for filing the bug report. I was able to reproduce the issue in a python 3.10 conda environment. It is indeed the old pandas version, for now I'd suggest you can simply upgrade to `pandas==1.4.3` until d2l releases the next version where we will bump the dependencies.

Or if you'd like you can also install it from the source.

**Comment by AnirudhDagar** [comment] 2022-07-15 22:53
@gladex I'll close this now, since we have fixed it in the latest release. You can use the latest version of the d2l package now.

**Closed by AnirudhDagar** 2022-07-15 22:53 UTC

**Comment by archerbj** [comment] 2023-04-25 12:59
Hi i am encountering the same issue. I just followed the  linear regression chapter to plot scatter for generated data. 

```
d2l.set_figsize()
d2l.plt.scatter(features[:, 1].detach().numpy(), labels.detach().numpy(), 1);
```

Neither the master branch nor 2.0.0 release  can fix this issue


Versions: 
python: 3.9.16 
d2l: 0.17.6 

```
Traceback (most recent call last):
  File "/Users/baixinjiang/coding/ai/deep-learning/pytorch/linear_regression/linear_regression.py", line 6, in <module>
    from d2l import torch as d2l
  File "/Users/baixinjiang/coding/python3/miniconda3/envs/d2l/lib/python3.9/site-packages/d2l/torch.py", line 32, in <module>
    import pandas as pd
  File "/Users/baixinjiang/coding/python3/miniconda3/envs/d2l/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/Users/baixinjiang/coding/python3/miniconda3/envs/d2l/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
(d2l) 
```
