### ISSUE TITLE
The issues after I run `d2lbook build lib`

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-en#1321] opened 2020-08-10 05:40 UTC
![image](https://user-images.githubusercontent.com/25657787/89754304-f59d3580-db0d-11ea-9dbb-eeeef69eec1a.png)

I found all code lost in
file:  ./chapter_preface/index.md
file:  ./chapter_preface/index.md

Then I found that after  I run `d2lbook activate all .\chapter_preface\index.md`

![image](https://user-images.githubusercontent.com/25657787/89754410-5af12680-db0e-11ea-88a7-1ff5461ad6eb.png)

![image](https://user-images.githubusercontent.com/25657787/89754521-d0f58d80-db0e-11ea-944f-721cc2843083.png)

another problem is that all slashes changed just because of my WIN10 OS
![image](https://user-images.githubusercontent.com/25657787/89754594-1a45dd00-db0f-11ea-96a0-158c2464a019.png)

**Comment by AnirudhDagar** [comment] 2020-08-10 08:53
@abhinavsp0730 can help with Windows related issues. I'm using a macOS.

**Comment by abhinavsp0730** [comment] 2020-08-10 09:04
I've answered here, https://github.com/d2l-ai/d2l-en/issues/1323#issuecomment-671242243

**Comment by StevenJokes** [comment] 2020-08-10 09:38
Wait for somebody to help windows' d2lbook.

**Comment by astonzhang** [comment] 2020-09-12 07:20
duplicate of https://github.com/d2l-ai/d2l-en/issues/1323

**Closed by astonzhang** 2020-09-12 07:20 UTC
